### ISSUE TITLE
The problem of NAN feature on Win5-LID dataset.

### ISSUE THREAD

**Issue by ZhengyuZhang96** [weizhou-geek/Tensor-NLFQ#3]
Hi, author! Thanks for your attractive work and code. Now I am trying to train a model on Win5-LID dataset, but there are 4 images whose features contian "NAN" after feature extraction with "Tensor-NLFQ/main.m". Specifically, these four images are: NN_greek_40, NN_dishes_40, NN_museum_40, NN_rosemary_40. 

Since NAN feature will lead to training errors, how to solve this problem? Looking forward to your reply! Thanks!

**Comment by weizhou-geek** [comment]
> Hi, author! Thanks for your attractive work and code. Now I am trying to train a model on Win5-LID dataset, but there are 4 images whose features contian "NAN" after feature extraction with "Tensor-NLFQ/main.m". Specifically, these four images are: NN_greek_40, NN_dishes_40, NN_museum_40, NN_rosemary_40.
> 
> Since NAN feature will lead to training errors, how to solve this problem? Looking forward to your reply! Thanks!

Hi, there! Thanks for your interest. Actually, you can set the NAN to zero or random number, and then test the results.

**Comment by ZhengyuZhang96** [comment]
Thanks a lot !
